### ISSUE TITLE
"transmission daemon require auth" when trying to connect to Docker container

### ISSUE THREAD

**Issue by steponmepls** [trim21/transmission-rpc#251]
# Description

I deployed transmission-daemon using a [docker](https://hub.docker.com/r/linuxserver/transmission) container but I am unable to connect to it with Flexget.

## Environment

- language version: Python 3.11.2
- app/lib/repo version: Flexget 3.5.34 / transmission-rpc 4.1.3 installed with pip / transmission 4.0.2

## How to reproduce

```yaml
templates:
  transmission:
    transmission:
      username: '{? accounts.transmission.user ?}'
      password: '{? accounts.transmission.pass ?}'
      port: 9092
```
```yaml
accounts:
  transmission:
    user: user
    pass: mypassword
```
Docker compose
```yaml
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission-seasonal
    environment:
      - PUID=998 # "docker" user id
      - PGID=115 # "docker" group id
      ..
      - USER=user
      - PASS=mypassword
      - WHITELIST=127.0.0.1,::1,192.168.1.*
    volumes:
      - /opt/dockers/transmission/seasonal/config:/config
      - /opt/dockers/transmission/seasonal/downloads:/downloads
      - /opt/dockers/transmission/seasonal/downloads/.watchdir:/watch
    ports:
      - 9092:9091
      - 51414:51413
      - 51414:51413/udp
    restart: unless-stopped
```
Settings.json
```json
    ..
    "rpc-authentication-required": true,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": false,
    "rpc-password": "{42a016302965d4f8678b44a4666eef09f816a444Qr4.Aahx",
    "rpc-port": 9091,
    "rpc-socket-mode": "0750",
    "rpc-url": "/transmission/",
    "rpc-username": "user",
    "rpc-whitelist": "127.0.0.1,::1,192.168.1.*",
    "rpc-whitelist-enabled": true,
```

## Expectations
I used the very same credentials I use with transmission-daemon 3.00 but I am not being able to connect. I double checked the credentials are correct by logging-in in the web ui after launching the docker container.

## Actual result
```
2023-03-27 03:42:15 VERBOSE  details       anime           Summary - Accepted: 1 (Rejected: 36 Undecided: 409 Failed: 0)
2023-03-27 03:42:15 CRITICAL plugin        anime           Error connecting to transmission: transmission daemon require auth
2023-03-27 03:42:15 WARNING  task          anime           Aborting task (plugin: transmission)
2023-03-27 03:42:16 CRITICAL plugin        cleaner         Error connecting to transmission: transmission daemon require auth
2023-03-27 03:42:16 WARNING  task          cleaner         Aborting task (plugin: from_transmission)
```
